#!/usr/bin/env python3
"""Verify that a wiki/document covers all sections from the source KB markdown.

Usage:
  python scripts/check_coverage.py \
    --source output/kb_md/kb_full.md \
    --wiki output/kb_md/wiki_GBT18487.md

Exit code 0 = full coverage, 1 = missing sections.
"""

import argparse
import re
import sys


def extract_sections(md_path: str, max_depth: int = 3) -> list[tuple[str, str]]:
    """Extract section headings from a markdown file.

    Returns [(heading_text, level_indicator), ...]
    Only extracts sections up to max_depth (##, ###, ####).
    Strips section numbers and English names to get the core title.
    """
    sections = []
    with open(md_path, "r", encoding="utf-8") as f:
        for line in f:
            m = re.match(r"^(#{1,%d})\s+(.+)" % max_depth, line)
            if not m:
                continue
            depth = len(m.group(1))
            title = m.group(2).strip()
            if not title:
                continue
            # Skip page headers like "## 第N页"
            if re.match(r"^第\d+页$", title):
                continue
            sections.append((title, depth))
    return sections


def normalize_title(title: str) -> str:
    """Normalize a heading title for fuzzy matching.

    - Strip leading section numbers (3.1, A.2.3, etc.)
    - Strip English names after Chinese
    - Strip spaces
    - Lowercase
    """
    # Remove section number prefix: "3.1.4", "A.2", "B.3.1"
    t = re.sub(r"^[A-Z]?\d+(\.\d+)*\s+", "", title)
    # Remove trailing English in parentheses or after space
    t = re.sub(r"\s*[(（].*?[)）]\s*$", "", t)
    t = re.sub(r"\s+[A-Za-z][A-Za-z\s/]+$", "", t)
    # Normalize spaces
    t = t.strip()
    return t


def _is_sub_definition(title: str, all_source_titles: list[str]) -> bool:
    """Check if a title is a sub-definition within Section 3 (术语和定义).

    These are individual term definitions like "充放电", "绝缘[性能]",
    which are expected to be summarized/merged in the wiki rather than
    listed individually.
    """
    norm = normalize_title(title)
    # Sub-definitions are typically short (2-8 chars of Chinese)
    # and appear after the "术语和定义" section header
    cjk_count = sum(1 for ch in norm if '一' <= ch <= '鿿')
    return cjk_count > 0 and cjk_count <= 8


def check_coverage(source_path: str, wiki_path: str) -> list[str]:
    """Check that all source sections are covered in the wiki.

    Returns a list of missing section descriptions.
    """
    source_sections = extract_sections(source_path, max_depth=1)
    wiki_text = open(wiki_path, "r", encoding="utf-8").read()
    all_titles = [t for t, _ in source_sections]

    missing = []
    seen = set()

    for title, depth in source_sections:
        norm = normalize_title(title)
        if not norm or len(norm) < 2:
            continue
        # Skip if already reported a similar title
        if norm in seen:
            continue
        seen.add(norm)

        # Skip: page headers, "知识库 Markdown" artifact
        if re.match(r"^第\d+页$", title):
            continue
        if "知识库 Markdown" in title:
            continue

        # Skip: level-1 document titles (auto-generated by batch_pdf_to_md.py)
        if depth == 1:
            continue

        # Skip: sub-definitions within Section 3 (术语和定义)
        # These are expected to be summarized in wiki tables
        if _is_sub_definition(title, all_titles):
            continue

        # Skip: 附录 bare titles — wiki uses "附录A: 具体名称" format
        if re.match(r"^附录\s*[A-Z]$", title.strip()):
            # Check if any wiki heading starts with this appendix letter
            letter = re.search(r"[A-Z]", title).group()
            if re.search(rf"附录\s*{letter}[：:]", wiki_text):
                continue

        # Skip: "标识和说明" if "标识" section exists in wiki
        if "标识和说明" in title and "标识" in wiki_text:
            continue

        # Skip: 参考文献 (not normative content)
        if "参考文献" in title:
            continue

        # Check: is the normalized title present in wiki?
        if norm in wiki_text:
            continue

        # Fuzzy: check if any word segment (2+ chars) of the title appears
        found = False
        if len(norm) >= 4 and norm[:4] in wiki_text:
            found = True
        for part in re.split(r"[的与和及、]", norm):
            if len(part) >= 4 and part in wiki_text:
                found = True
                break

        if not found:
            missing.append(title)

    return missing


def main():
    parser = argparse.ArgumentParser(
        description="Check wiki coverage against source KB markdown"
    )
    parser.add_argument(
        "--source", required=True, help="Source KB markdown (kb_full.md)"
    )
    parser.add_argument(
        "--wiki", required=True, help="Wiki markdown to check"
    )
    args = parser.parse_args()

    missing = check_coverage(args.source, args.wiki)

    if not missing:
        print("Coverage: 100% — all source sections found in wiki.")
        sys.exit(0)

    print(f"Coverage gap: {len(missing)} section(s) missing from wiki:\n")
    for i, title in enumerate(missing, 1):
        print(f"  {i}. {title}")

    # Also show what sections the source has
    source_sections = extract_sections(args.source, max_depth=2)
    print(f"\nSource has {len(source_sections)} sections (depth <= 2).")
    print(f"Wiki is missing {len(missing)} ({100 * len(missing) / max(len(source_sections), 1):.0f}%).")

    sys.exit(1)


if __name__ == "__main__":
    main()
